apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: multi-tier-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-html
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: frontend-html
        configMap:
          name: frontend-html
          items:
          - key: index.html
            path: index.html
      - name: nginx-conf
        configMap:
          name: frontend-html
          items:
          - key: default.conf
            path: default.conf
